In [ ]:
%config IPCompleter.greedy=True

### Create a numpy array of temperatures in Celsius and convert to Fahrenheit

In [4]:
import numpy as np

celsiusValues = np.array([10,16,20,30])
fahrenheitValues = (celsiusValues * 9 / 5 +32)
print(fahrenheitValues)

[50.  60.8 68.  86. ]


### Arange function. arange(start, stop, step, data type). stop value excluded

In [2]:
import numpy as np
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [4]:
b = np.arange(10.5)
print(b)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [5]:
c = np.arange(0.5, 10.5, 1.2, int)
print(c)

[0 1 2 3 4 5 6 7 8]


## Linspace
### syntax linspace(start, stop, num=50, endpoint=True, retstep=False)

In [6]:
import numpy as np

# by default size is 50
x = np.linspace(1,10)
print("Size is: ",x.size)
print(x)


Size is:  50
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [7]:
# creating specific size with linspace
x = np.linspace(1,10,10)
print("Size is: ",x.size)
print(x)

Size is:  10
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [10]:
# excluding end number
x = np.linspace(1,10,10, endpoint = False )
print("Size is: ",x.size)
print(x)

Size is:  10
[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]


In [11]:
# step size(common differnce)
sample, spacing = np.linspace(1,10,6, retstep=True)
print('Spacing: ', spacing)
print(sample)

Spacing:  1.8
[ 1.   2.8  4.6  6.4  8.2 10. ]


## Zero dimensinal arrays

In [2]:
import numpy as np
x = np.array(42)
print("x: ", x)
print("Type: ", type(x))
print("Dimension: ", np.ndim(x))

x:  42
Type:  <class 'numpy.ndarray'>
Dimension:  0


## One dimensional Array

In [3]:
x = np.array((1, 2,3))
print("x: ", x)
print("Type: ", x.dtype)
print("Dimension: ", np.ndim(x))

x:  [1 2 3]
Type:  int64
Dimension:  1


## Two Dimensional Arrays

In [10]:
A = np.array([[1,2,3], 
              [4,5,6]])
print(A)
print(A.dtype)
print(A.ndim)
# shape function returns row and column
print(np.shape(A))
# Transpose matrix using shape function
B = A
B.shape = (3,2)
print(B)

[[1 2 3]
 [4 5 6]]
int64
2
(2, 3)
[[1 2]
 [3 4]
 [5 6]]


## Slicing A[start:stop:step]   stop excluded

In [15]:
S = np.linspace(11,20,10)
print(S)

[11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]


In [16]:
print(S[2:5])

[13. 14. 15.]


In [17]:
print(S[:4])

[11. 12. 13. 14.]


In [18]:
print(S[6:])

[17. 18. 19. 20.]


In [19]:
print(S[:])

[11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]


## A wired behavior

In [22]:

A = np.arange(12)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [23]:
B = A.reshape(3,4)
print(A)
print(B)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [24]:
A[0] = 1000
print(A)
print(B)

[1000    1    2    3    4    5    6    7    8    9   10   11]
[[1000    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]


## Arrays with zeros and ones

In [26]:
x = np.zeros((3,2), dtype = int)
print(x)

[[0 0]
 [0 0]
 [0 0]]


In [27]:
x = np.ones((3,2), dtype = int)
print(x)

[[1 1]
 [1 1]
 [1 1]]


In [29]:
a = np.array([[1,2],[4,5]])
x = np.zeros_like(a)
print(a)
print(x)

[[1 2]
 [4 5]]
[[0 0]
 [0 0]]


In [31]:
i = np.identity(3,dtype=int)
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### 1) Create an arbitrary one dimensional array called "v"

In [35]:
a = np.array([2,3,4,55,66,32,64,24,1])
print(a)

[ 2  3  4 55 66 32 64 24  1]


### 2) Create a new array which consists of the odd indices of previously created array "v"

In [38]:
b = a.copy()
b = b[1::2]
print(b)

[ 3 55 32 24]


### 3) Create a new array in backwards ordering from v.

In [39]:
reverse = a[::-1]
print(reverse)

[ 1 24 64 32 66 55  4  3  2]


### 4)Create a two dimensional array called "m"

In [49]:
m = np.array([ [1,2,3],
              [4,5,6],
             [7,8,9]])

### 5) Create a new array from m, in which the elements of each row are in reverse order.

In [50]:
reverse_row_element = m[:,::-1]
print(reverse_row_element)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


### 6) Another one, where the rows are in reverse order

In [51]:
reverse_row = m[::-1]
print(reverse_row)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


### 7) Create an array from m, where columns and rows are in reverse order.

In [52]:
reverse_array = m[::-1,::-1]
print(reverse_array)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 8) Cut of the first and last row and the first and last column.

In [53]:
print(m[1:-1,1:-1])

[[5]]
