In [1]:
import numpy as np

## List vs numpyarray

#### Numpy array is faster

In [2]:
# list 
list = [1,2,3,4]
print(list)
type(list)

[1, 2, 3, 4]


list

In [3]:
# numpy array
np_array = np.array([1,2,3,4])
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

In [4]:
np_array.shape

(4,)

## 2D array

In [6]:
two_d_array = np.array([(1,2,3,4),(5,6,7,8)])
print(two_d_array)
two_d_array.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [8]:
c = np.array([(1,2,3),(4,5,6)], dtype = float)
print(c)

[[1. 2. 3.]
 [4. 5. 6.]]


## Initial place holder

In [10]:
#create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# create an array with specific value
z = np.full((4,5),5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [14]:
# create an identity matraix
i = np.eye(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
#create a random array
a = np.random.random((3,4))
print(a)

[[0.97170113 0.2807248  0.716234   0.50635417]
 [0.16664626 0.83688917 0.90127418 0.2587691 ]
 [0.04650061 0.54532629 0.38661091 0.27375806]]


In [21]:
# random integer values 

c = np.random.randint(10,100,(10))
print(c)

d = np.random.randint(20,30,(4,4))

print(d)

[33 90 84 15 92 93 19 45 92 77]
[[29 21 27 20]
 [24 24 23 25]
 [24 25 21 28]
 [24 20 23 22]]


In [23]:
# create array of evenly spaced value

e = np.linspace(1,10,5)
print(e)

[ 1.    3.25  5.5   7.75 10.  ]


In [24]:
# array of evenly spaced value with step

f = np.arange(10,30,5)
print(f)

[10 15 20 25]


In [27]:
# convert a list to nparray
list = [1,2,3,4,5,6,7]
np_array = np.array(list)
print(np_array)
print(type(np_array))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


## Analyzing np array

In [28]:
c = np.random.randint(10,90,(4,5))

print(c)

[[22 10 41 23 48]
 [58 33 43 61 56]
 [31 83 10 22 80]
 [29 77 60 52 76]]


In [29]:
# array dimension
print(c.shape)

(4, 5)


In [30]:
# number of dimension

print(c.ndim)

2


In [31]:
# total number of element in an array
print(c.size)

20


In [32]:
#chicking datatype
print(c.dtype)

int64


## Mathematical Operation

In [33]:
list  = [1,2,3]
list_2 = [4,5,6]
print(list + list_2)  #concatinate

[1, 2, 3, 4, 5, 6]


In [ ]:
a = np.ar