In [ ]:
%config IPCompleter.greedy=True

### Create a numpy array of temperatures in Celsius and convert to Fahrenheit

In [4]:
import numpy as np

celsiusValues = np.array([10,16,20,30])
fahrenheitValues = (celsiusValues * 9 / 5 +32)
print(fahrenheitValues)

[50.  60.8 68.  86. ]


### Arange function. arange(start, stop, step, data type). stop value excluded

In [2]:
import numpy as np
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [4]:
b = np.arange(10.5)
print(b)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [5]:
c = np.arange(0.5, 10.5, 1.2, int)
print(c)

[0 1 2 3 4 5 6 7 8]


## Linspace
### syntax linspace(start, stop, num=50, endpoint=True, retstep=False)

In [6]:
import numpy as np

# by default size is 50
x = np.linspace(1,10)
print("Size is: ",x.size)
print(x)


Size is:  50
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [7]:
# creating specific size with linspace
x = np.linspace(1,10,10)
print("Size is: ",x.size)
print(x)

Size is:  10
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [10]:
# excluding end number
x = np.linspace(1,10,10, endpoint = False )
print("Size is: ",x.size)
print(x)

Size is:  10
[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]


In [11]:
# step size(common differnce)
sample, spacing = np.linspace(1,10,6, retstep=True)
print('Spacing: ', spacing)
print(sample)

Spacing:  1.8
[ 1.   2.8  4.6  6.4  8.2 10. ]
